apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster

spec:
  instances: 3
  storage:
    size: 1Gi

  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      shared_buffers: "256MB"
      work_mem: "64MB"
      max_connections: "100"
      max_worker_processes: "60"

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE DATABASE mydb;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: pg-cluster-metrics
# spec:
#   selector:
#     matchLabels:
#       cnpg.io/cluster: pg-cluster
#   podMetricsEndpoints:
#     - port: metrics
#
